### PR TITLE
Cleaning up the house

### PR DESCRIPTION
**Pull request by alaxalves**
## Proposed Changes

Organizing files.

## Type of Change

What kind of changes this Pull Request introduces to Falko?
_`x` to what it applies_

- [x] Bugfix
- [ ] New Feature

## Checklist

_`x`to what it applies. If not sure about some topics, don't hesitate to ask. We're here to help!_

- [x] Pull Request's name is self-explanatory and its in English.
- [x] There are no _Rubocop_ issues.
- [x] Travis build has success (tests, code climate and codacy checks).
- [x] Pull Request is linked to an existing issue.
- [x] Seeds have been created to the new User Stories.

### CODE REVIEW

**Comment by alaxalves** [comment]
Build's not passing because of issue https://github.com/travis-ci/travis-ci/issues/9573

**Comment by alaxalves** [comment]
I'll revert this for now, but when version 3.5 is supported we'll change.

**Comment by alaxalves** [comment]
@matheussbernardo @MatheusRich The build now is passing :+1:

**Comment by alaxalves** [comment]
Fixes https://github.com/falko-org/Falko-API/issues/212

**Comment by cantuariavc** [comment]
Travis is passing, should I accept, @alaxalves?

**Comment by alaxalves** [comment]
@cantuariavc Have you checked the files?? If you find any incosistency please comment

**Review by cantuariavc — DISMISSED** [review]

**Comment by cantuariavc** [comment]
Now, you have to resolve the conflicts

**Pull request merged**
